
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/speed_kill_system?serviceTimezone=UTC
      username: root
      password: wu@xiaoting0308@
  main:
    allow-circular-references: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates
  redis:
    password:
    host: localhost
    database: 0
    port: 6379



mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jetcache的基本配置
jetcache:
  remote:
     default:
       type: redis
       host: localhost
       port: 6379
       valueEncode: java
       valueDecode: java
       poolConfig:
         maxTotal: 50


#spring:
#  profiles:
#    active: dev
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#server:
#  port: 80
#
#---
#spring:
#  config:
#    activate:
#      on-profile: pro
#server:
server:
  port: 80
#  port: 81
